#ifndef __LABSC_AUTH_API_H
#define __LABSC_AUTH_API_H

typedef enum
{
  AUTH_RESET=0x1,
  AUTH_CONFIGURING=0x2,
  AUTH_JOINING=0x4,
  AUTH_JOINED = 0x8,
  AUTH_ERROR = 0x10 
} AUTH_STATE;

#define AUTH_STATE_ALL (AUTH_RESET | AUTH_CONFIGURING | AUTH_JOINING )


#define AUTH_EVENT_JOINER_ERROR_NONE 0x1
#define AUTH_EVENT_JOINER_ERROR_SECURITY 0x2
#define AUTH_EVENT_JOINER_ERROR_NOT_FOUND 0x4
#define AUTH_EVENT_JOINER_ERROR_RESPONSE_TIMEOUT 0x8
#define AUTH_EVENT_TIME 0x10




BaseType_t labsc_auth_api_init();

#endif